//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace phone_BETA_1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CHITIET_HOADON
    {
        public int ID_HD { get; set; }
        public int ID_SP { get; set; }
        public Nullable<int> SoLuong { get; set; }
        public Nullable<double> Price_CTHD { get; set; }
        public string Name_SP { get; set; }
        public string Photo { get; set; }
    
        public virtual HOADON HOADON { get; set; }
        public virtual SANPHAM SANPHAM { get; set; }
    }
}
