//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace phone_BETA_1.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    using System.ComponentModel.DataAnnotations;

    public partial class CHITIET_HOADON
    {
        [DisplayName("Mã hóa đơn:")]
        public int ID_HD { get; set; }
        [DisplayName("Mã sản phẩm:")]
        public int ID_SP { get; set; }
        [DisplayName("Số lượng:")]
        public Nullable<int> SoLuong { get; set; }
        [DisplayName("Giá tiền:")]
        public Nullable<double> Price_CTHD { get; set; }
        [DisplayName("Tên sản phẩm:")]
        public string Name_SP { get; set; }
        [DisplayName("Ảnh sản phẩm:")]
        public string Photo { get; set; }

        public virtual HOADON HOADON { get; set; }
        public virtual SANPHAM SANPHAM { get; set; }
    }
}
