//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace phone_BETA_1.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    using System.ComponentModel.DataAnnotations;

    public partial class ChiTietSanPham_Result1
    {
        [DisplayName("Mã sản phẩm:")]
        public int Mã_sản_phẩm { get; set; }
        [DisplayName("Tên sản phẩm:")]
        public string Tên_sản_phẩm { get; set; }
        [DisplayName("Giá tiền:")]
        public Nullable<double> Giá_sản_phẩm { get; set; }
        [DisplayName("Năm sản xuất:")]
        public Nullable<double> Năm_sản_xuất { get; set; }
        [DisplayName("Trả góp:")]
        public Nullable<double> Trả_góp { get; set; }
        [DisplayName("Tình trạng:")]
        public string Tình_trạng { get; set; }
        [DisplayName("Phụ kiện:")]
        public string Phụ_kiện { get; set; }
        public string Ảnh { get; set; }
        [DisplayName("Hãng sản xuất:")]
        public string Hãng_sản_suất { get; set; }
        [DisplayName("Loại hàng:")]
        public string Loại_hàng { get; set; }
        [DisplayName("Nhóm hàng:")]
        public string Nhóm_hàng { get; set; }
    }
}
