//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace phone_BETA_1.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    using System.ComponentModel.DataAnnotations;

    public partial class HOADON
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public HOADON()
        {
            this.CHITIET_HOADON = new HashSet<CHITIET_HOADON>();
        }

        [DisplayName("Mã hóa đơn:")]
        public int ID_HD { get; set; }
        [DisplayName("Tên khách hàng:")]
        public string Name_Customer { get; set; }
        [DisplayName("Ngày đặt hàng:")]
        [DataType(DataType.Date)]
        [DisplayFormat(DataFormatString = "{0: yyyy-MM-dd}", ApplyFormatInEditMode = true)]
        public Nullable<System.DateTime> DateCreate { get; set; }
        [DisplayName("Số điện thoại:")]
        public string SDT { get; set; }
        [DisplayName("Mã khách hàng:")]
        public Nullable<int> ID_Customer { get; set; }
        [DisplayName("Địa chỉ:")]
        public string DiaChi { get; set; }
        public string Email { get; set; }
        [DisplayName("Tình trạng:")]
        public string TinhTrang { get; set; }
        [DisplayName("Tổng tiền:")]
        public string TongTien { get; set; }

        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CHITIET_HOADON> CHITIET_HOADON { get; set; }
        public virtual KHACHHANG KHACHHANG { get; set; }
    }
}
