//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace phone_BETA_1.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class phone_BETAEntities : DbContext
    {
        public phone_BETAEntities()
            : base("name=phone_BETAEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<ADMIN> ADMINS { get; set; }
        public virtual DbSet<CHITIET_HOADON> CHITIET_HOADON { get; set; }
        public virtual DbSet<CLIENT> CLIENTS { get; set; }
        public virtual DbSet<HANG_SX> HANG_SX { get; set; }
        public virtual DbSet<HOADON> HOADONs { get; set; }
        public virtual DbSet<KHACHHANG> KHACHHANGs { get; set; }
        public virtual DbSet<LOAIHANG> LOAIHANGs { get; set; }
        public virtual DbSet<NHANVIEN> NHANVIENs { get; set; }
        public virtual DbSet<NHOMHANG> NHOMHANGs { get; set; }
        public virtual DbSet<SANPHAM> SANPHAMs { get; set; }
    
        public virtual ObjectResult<ChiTietSanPham_Result> ChiTietSanPham(string iD_SP)
        {
            var iD_SPParameter = iD_SP != null ?
                new ObjectParameter("ID_SP", iD_SP) :
                new ObjectParameter("ID_SP", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<ChiTietSanPham_Result>("ChiTietSanPham", iD_SPParameter);
        }
    
        public virtual ObjectResult<HoaDon_SearchHD_1_Result> HoaDon_SearchHD_1(string dateFrom, string dateTo)
        {
            var dateFromParameter = dateFrom != null ?
                new ObjectParameter("DateFrom", dateFrom) :
                new ObjectParameter("DateFrom", typeof(string));
    
            var dateToParameter = dateTo != null ?
                new ObjectParameter("DateTo", dateTo) :
                new ObjectParameter("DateTo", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<HoaDon_SearchHD_1_Result>("HoaDon_SearchHD_1", dateFromParameter, dateToParameter);
        }
    
        public virtual ObjectResult<HoaDon_SearchHD_2_Result> HoaDon_SearchHD_2(string name_Customer, string dateFrom, string dateTo)
        {
            var name_CustomerParameter = name_Customer != null ?
                new ObjectParameter("Name_Customer", name_Customer) :
                new ObjectParameter("Name_Customer", typeof(string));
    
            var dateFromParameter = dateFrom != null ?
                new ObjectParameter("DateFrom", dateFrom) :
                new ObjectParameter("DateFrom", typeof(string));
    
            var dateToParameter = dateTo != null ?
                new ObjectParameter("DateTo", dateTo) :
                new ObjectParameter("DateTo", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<HoaDon_SearchHD_2_Result>("HoaDon_SearchHD_2", name_CustomerParameter, dateFromParameter, dateToParameter);
        }
    
        public virtual ObjectResult<HoaDon_SearchHD_3_Result> HoaDon_SearchHD_3(string name_Customer)
        {
            var name_CustomerParameter = name_Customer != null ?
                new ObjectParameter("Name_Customer", name_Customer) :
                new ObjectParameter("Name_Customer", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<HoaDon_SearchHD_3_Result>("HoaDon_SearchHD_3", name_CustomerParameter);
        }
    
        public virtual ObjectResult<HoaDon_SearchHoaDon_Result> HoaDon_SearchHoaDon(string tinhTrang)
        {
            var tinhTrangParameter = tinhTrang != null ?
                new ObjectParameter("TinhTrang", tinhTrang) :
                new ObjectParameter("TinhTrang", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<HoaDon_SearchHoaDon_Result>("HoaDon_SearchHoaDon", tinhTrangParameter);
        }
    
        public virtual int Huy_HoaDon(string iD_HD)
        {
            var iD_HDParameter = iD_HD != null ?
                new ObjectParameter("ID_HD", iD_HD) :
                new ObjectParameter("ID_HD", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("Huy_HoaDon", iD_HDParameter);
        }
    
        public virtual ObjectResult<KhachHang_SearchKhachHang_Result> KhachHang_SearchKhachHang(string name_Customer)
        {
            var name_CustomerParameter = name_Customer != null ?
                new ObjectParameter("Name_Customer", name_Customer) :
                new ObjectParameter("Name_Customer", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<KhachHang_SearchKhachHang_Result>("KhachHang_SearchKhachHang", name_CustomerParameter);
        }
    
        public virtual ObjectResult<SanPham_Search_3_Result> SanPham_Search_3(string iD_NH, string iD_HSX, string iD_LH)
        {
            var iD_NHParameter = iD_NH != null ?
                new ObjectParameter("ID_NH", iD_NH) :
                new ObjectParameter("ID_NH", typeof(string));
    
            var iD_HSXParameter = iD_HSX != null ?
                new ObjectParameter("ID_HSX", iD_HSX) :
                new ObjectParameter("ID_HSX", typeof(string));
    
            var iD_LHParameter = iD_LH != null ?
                new ObjectParameter("ID_LH", iD_LH) :
                new ObjectParameter("ID_LH", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SanPham_Search_3_Result>("SanPham_Search_3", iD_NHParameter, iD_HSXParameter, iD_LHParameter);
        }
    
        public virtual ObjectResult<SanPham_SearchHSX_Result> SanPham_SearchHSX(string iD_HSX)
        {
            var iD_HSXParameter = iD_HSX != null ?
                new ObjectParameter("ID_HSX", iD_HSX) :
                new ObjectParameter("ID_HSX", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SanPham_SearchHSX_Result>("SanPham_SearchHSX", iD_HSXParameter);
        }
    
        public virtual ObjectResult<SanPham_SearchLH_Result> SanPham_SearchLH(string iD_LH)
        {
            var iD_LHParameter = iD_LH != null ?
                new ObjectParameter("ID_LH", iD_LH) :
                new ObjectParameter("ID_LH", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SanPham_SearchLH_Result>("SanPham_SearchLH", iD_LHParameter);
        }
    
        public virtual ObjectResult<SanPham_SearchNH_Result> SanPham_SearchNH(string iD_NH)
        {
            var iD_NHParameter = iD_NH != null ?
                new ObjectParameter("ID_NH", iD_NH) :
                new ObjectParameter("ID_NH", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SanPham_SearchNH_Result>("SanPham_SearchNH", iD_NHParameter);
        }
    
        public virtual ObjectResult<SanPham_SearchTenSP_Result> SanPham_SearchTenSP(string name_SP)
        {
            var name_SPParameter = name_SP != null ?
                new ObjectParameter("Name_SP", name_SP) :
                new ObjectParameter("Name_SP", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SanPham_SearchTenSP_Result>("SanPham_SearchTenSP", name_SPParameter);
        }
    
        public virtual ObjectResult<SanPham_SearchTinhTrang_Result> SanPham_SearchTinhTrang(string tinhTrang)
        {
            var tinhTrangParameter = tinhTrang != null ?
                new ObjectParameter("TinhTrang", tinhTrang) :
                new ObjectParameter("TinhTrang", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SanPham_SearchTinhTrang_Result>("SanPham_SearchTinhTrang", tinhTrangParameter);
        }
    
        public virtual int Xoa_SanPham(string iD_SP)
        {
            var iD_SPParameter = iD_SP != null ?
                new ObjectParameter("ID_SP", iD_SP) :
                new ObjectParameter("ID_SP", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("Xoa_SanPham", iD_SPParameter);
        }
    
        public virtual int XoaTK_KHACHHANG(string iD_Customer)
        {
            var iD_CustomerParameter = iD_Customer != null ?
                new ObjectParameter("ID_Customer", iD_Customer) :
                new ObjectParameter("ID_Customer", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("XoaTK_KHACHHANG", iD_CustomerParameter);
        }
    
        public virtual int XoaTK_NHANVIEN(string iD_Admin)
        {
            var iD_AdminParameter = iD_Admin != null ?
                new ObjectParameter("ID_Admin", iD_Admin) :
                new ObjectParameter("ID_Admin", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("XoaTK_NHANVIEN", iD_AdminParameter);
        }
    }
}
