//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace phone_BETA_1.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class phone_BETAEntities1 : DbContext
    {
        public phone_BETAEntities1()
            : base("name=phone_BETAEntities1")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<ADMIN> ADMINS { get; set; }
        public virtual DbSet<CHITIET_HOADON> CHITIET_HOADON { get; set; }
        public virtual DbSet<HANG_SX> HANG_SX { get; set; }
        public virtual DbSet<HOADON> HOADONs { get; set; }
        public virtual DbSet<KHACHHANG> KHACHHANGs { get; set; }
        public virtual DbSet<LOAIHANG> LOAIHANGs { get; set; }
        public virtual DbSet<NHANVIEN> NHANVIENs { get; set; }
        public virtual DbSet<NHOMHANG> NHOMHANGs { get; set; }
        public virtual DbSet<SANPHAM> SANPHAMs { get; set; }
        public virtual DbSet<sysdiagram> sysdiagrams { get; set; }
        public virtual DbSet<CLIENT> CLIENTS { get; set; }
    
        public virtual int sp_alterdiagram(string diagramname, Nullable<int> owner_id, Nullable<int> version, byte[] definition)
        {
            var diagramnameParameter = diagramname != null ?
                new ObjectParameter("diagramname", diagramname) :
                new ObjectParameter("diagramname", typeof(string));
    
            var owner_idParameter = owner_id.HasValue ?
                new ObjectParameter("owner_id", owner_id) :
                new ObjectParameter("owner_id", typeof(int));
    
            var versionParameter = version.HasValue ?
                new ObjectParameter("version", version) :
                new ObjectParameter("version", typeof(int));
    
            var definitionParameter = definition != null ?
                new ObjectParameter("definition", definition) :
                new ObjectParameter("definition", typeof(byte[]));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_alterdiagram", diagramnameParameter, owner_idParameter, versionParameter, definitionParameter);
        }
    
        public virtual int sp_creatediagram(string diagramname, Nullable<int> owner_id, Nullable<int> version, byte[] definition)
        {
            var diagramnameParameter = diagramname != null ?
                new ObjectParameter("diagramname", diagramname) :
                new ObjectParameter("diagramname", typeof(string));
    
            var owner_idParameter = owner_id.HasValue ?
                new ObjectParameter("owner_id", owner_id) :
                new ObjectParameter("owner_id", typeof(int));
    
            var versionParameter = version.HasValue ?
                new ObjectParameter("version", version) :
                new ObjectParameter("version", typeof(int));
    
            var definitionParameter = definition != null ?
                new ObjectParameter("definition", definition) :
                new ObjectParameter("definition", typeof(byte[]));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_creatediagram", diagramnameParameter, owner_idParameter, versionParameter, definitionParameter);
        }
    
        public virtual int sp_dropdiagram(string diagramname, Nullable<int> owner_id)
        {
            var diagramnameParameter = diagramname != null ?
                new ObjectParameter("diagramname", diagramname) :
                new ObjectParameter("diagramname", typeof(string));
    
            var owner_idParameter = owner_id.HasValue ?
                new ObjectParameter("owner_id", owner_id) :
                new ObjectParameter("owner_id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_dropdiagram", diagramnameParameter, owner_idParameter);
        }
    
        public virtual ObjectResult<sp_helpdiagramdefinition_Result> sp_helpdiagramdefinition(string diagramname, Nullable<int> owner_id)
        {
            var diagramnameParameter = diagramname != null ?
                new ObjectParameter("diagramname", diagramname) :
                new ObjectParameter("diagramname", typeof(string));
    
            var owner_idParameter = owner_id.HasValue ?
                new ObjectParameter("owner_id", owner_id) :
                new ObjectParameter("owner_id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_helpdiagramdefinition_Result>("sp_helpdiagramdefinition", diagramnameParameter, owner_idParameter);
        }
    
        public virtual ObjectResult<sp_helpdiagrams_Result> sp_helpdiagrams(string diagramname, Nullable<int> owner_id)
        {
            var diagramnameParameter = diagramname != null ?
                new ObjectParameter("diagramname", diagramname) :
                new ObjectParameter("diagramname", typeof(string));
    
            var owner_idParameter = owner_id.HasValue ?
                new ObjectParameter("owner_id", owner_id) :
                new ObjectParameter("owner_id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_helpdiagrams_Result>("sp_helpdiagrams", diagramnameParameter, owner_idParameter);
        }
    
        public virtual int sp_renamediagram(string diagramname, Nullable<int> owner_id, string new_diagramname)
        {
            var diagramnameParameter = diagramname != null ?
                new ObjectParameter("diagramname", diagramname) :
                new ObjectParameter("diagramname", typeof(string));
    
            var owner_idParameter = owner_id.HasValue ?
                new ObjectParameter("owner_id", owner_id) :
                new ObjectParameter("owner_id", typeof(int));
    
            var new_diagramnameParameter = new_diagramname != null ?
                new ObjectParameter("new_diagramname", new_diagramname) :
                new ObjectParameter("new_diagramname", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_renamediagram", diagramnameParameter, owner_idParameter, new_diagramnameParameter);
        }
    
        public virtual int sp_upgraddiagrams()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_upgraddiagrams");
        }
    
        public virtual int Huy_HoaDon(string iD_HD)
        {
            var iD_HDParameter = iD_HD != null ?
                new ObjectParameter("ID_HD", iD_HD) :
                new ObjectParameter("ID_HD", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("Huy_HoaDon", iD_HDParameter);
        }
    
        public virtual ObjectResult<KhachHang_SearchKhachHang_Result> KhachHang_SearchKhachHang(string name_Customer)
        {
            var name_CustomerParameter = name_Customer != null ?
                new ObjectParameter("Name_Customer", name_Customer) :
                new ObjectParameter("Name_Customer", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<KhachHang_SearchKhachHang_Result>("KhachHang_SearchKhachHang", name_CustomerParameter);
        }
    
        public virtual int Xoa_SanPham(string iD_SP)
        {
            var iD_SPParameter = iD_SP != null ?
                new ObjectParameter("ID_SP", iD_SP) :
                new ObjectParameter("ID_SP", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("Xoa_SanPham", iD_SPParameter);
        }
    
        public virtual int XoaTK_KHACHHANG(string iD_Customer)
        {
            var iD_CustomerParameter = iD_Customer != null ?
                new ObjectParameter("ID_Customer", iD_Customer) :
                new ObjectParameter("ID_Customer", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("XoaTK_KHACHHANG", iD_CustomerParameter);
        }
    
        public virtual ObjectResult<KHACHHANG> Search_Customers(string name_Customer)
        {
            var name_CustomerParameter = name_Customer != null ?
                new ObjectParameter("Name_Customer", name_Customer) :
                new ObjectParameter("Name_Customer", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<KHACHHANG>("Search_Customers", name_CustomerParameter);
        }
    
        public virtual ObjectResult<KHACHHANG> Search_Customers(string name_Customer, MergeOption mergeOption)
        {
            var name_CustomerParameter = name_Customer != null ?
                new ObjectParameter("Name_Customer", name_Customer) :
                new ObjectParameter("Name_Customer", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<KHACHHANG>("Search_Customers", mergeOption, name_CustomerParameter);
        }
    
        public virtual ObjectResult<HOADON> Search_Bills(string name_Customer, Nullable<System.DateTime> dateCreate)
        {
            var name_CustomerParameter = name_Customer != null ?
                new ObjectParameter("Name_Customer", name_Customer) :
                new ObjectParameter("Name_Customer", typeof(string));
    
            var dateCreateParameter = dateCreate.HasValue ?
                new ObjectParameter("DateCreate", dateCreate) :
                new ObjectParameter("DateCreate", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<HOADON>("Search_Bills", name_CustomerParameter, dateCreateParameter);
        }
    
        public virtual ObjectResult<HOADON> Search_Bills(string name_Customer, Nullable<System.DateTime> dateCreate, MergeOption mergeOption)
        {
            var name_CustomerParameter = name_Customer != null ?
                new ObjectParameter("Name_Customer", name_Customer) :
                new ObjectParameter("Name_Customer", typeof(string));
    
            var dateCreateParameter = dateCreate.HasValue ?
                new ObjectParameter("DateCreate", dateCreate) :
                new ObjectParameter("DateCreate", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<HOADON>("Search_Bills", mergeOption, name_CustomerParameter, dateCreateParameter);
        }
    
        public virtual ObjectResult<HoaDon_SearchHD_Result> HoaDon_SearchHD(string name_Customer, string dateCreate)
        {
            var name_CustomerParameter = name_Customer != null ?
                new ObjectParameter("Name_Customer", name_Customer) :
                new ObjectParameter("Name_Customer", typeof(string));
    
            var dateCreateParameter = dateCreate != null ?
                new ObjectParameter("DateCreate", dateCreate) :
                new ObjectParameter("DateCreate", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<HoaDon_SearchHD_Result>("HoaDon_SearchHD", name_CustomerParameter, dateCreateParameter);
        }
    
        public virtual ObjectResult<HOADON> SearchHoaDon(string name_Customer, string dateCreate)
        {
            var name_CustomerParameter = name_Customer != null ?
                new ObjectParameter("Name_Customer", name_Customer) :
                new ObjectParameter("Name_Customer", typeof(string));
    
            var dateCreateParameter = dateCreate != null ?
                new ObjectParameter("DateCreate", dateCreate) :
                new ObjectParameter("DateCreate", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<HOADON>("SearchHoaDon", name_CustomerParameter, dateCreateParameter);
        }
    
        public virtual ObjectResult<HOADON> SearchHoaDon(string name_Customer, string dateCreate, MergeOption mergeOption)
        {
            var name_CustomerParameter = name_Customer != null ?
                new ObjectParameter("Name_Customer", name_Customer) :
                new ObjectParameter("Name_Customer", typeof(string));
    
            var dateCreateParameter = dateCreate != null ?
                new ObjectParameter("DateCreate", dateCreate) :
                new ObjectParameter("DateCreate", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<HOADON>("SearchHoaDon", mergeOption, name_CustomerParameter, dateCreateParameter);
        }
    
        public virtual ObjectResult<HoaDon_SearchHD_2_Result> HoaDon_SearchHD_2(string dateCreate)
        {
            var dateCreateParameter = dateCreate != null ?
                new ObjectParameter("DateCreate", dateCreate) :
                new ObjectParameter("DateCreate", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<HoaDon_SearchHD_2_Result>("HoaDon_SearchHD_2", dateCreateParameter);
        }
    
        public virtual ObjectResult<HOADON> SearchHD_2(string dateCreate)
        {
            var dateCreateParameter = dateCreate != null ?
                new ObjectParameter("DateCreate", dateCreate) :
                new ObjectParameter("DateCreate", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<HOADON>("SearchHD_2", dateCreateParameter);
        }
    
        public virtual ObjectResult<HOADON> SearchHD_2(string dateCreate, MergeOption mergeOption)
        {
            var dateCreateParameter = dateCreate != null ?
                new ObjectParameter("DateCreate", dateCreate) :
                new ObjectParameter("DateCreate", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<HOADON>("SearchHD_2", mergeOption, dateCreateParameter);
        }
    
        public virtual ObjectResult<SanPham_Search_Result> SanPham_Search(Nullable<int> iD_NH, Nullable<int> iD_HSX, Nullable<int> iD_LH)
        {
            var iD_NHParameter = iD_NH.HasValue ?
                new ObjectParameter("ID_NH", iD_NH) :
                new ObjectParameter("ID_NH", typeof(int));
    
            var iD_HSXParameter = iD_HSX.HasValue ?
                new ObjectParameter("ID_HSX", iD_HSX) :
                new ObjectParameter("ID_HSX", typeof(int));
    
            var iD_LHParameter = iD_LH.HasValue ?
                new ObjectParameter("ID_LH", iD_LH) :
                new ObjectParameter("ID_LH", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SanPham_Search_Result>("SanPham_Search", iD_NHParameter, iD_HSXParameter, iD_LHParameter);
        }
    
        public virtual ObjectResult<SanPham_SearchHSX_Result> SanPham_SearchHSX(string iD_HSX)
        {
            var iD_HSXParameter = iD_HSX != null ?
                new ObjectParameter("ID_HSX", iD_HSX) :
                new ObjectParameter("ID_HSX", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SanPham_SearchHSX_Result>("SanPham_SearchHSX", iD_HSXParameter);
        }
    
        public virtual ObjectResult<SanPham_SearchLH_Result> SanPham_SearchLH(string iD_LH)
        {
            var iD_LHParameter = iD_LH != null ?
                new ObjectParameter("ID_LH", iD_LH) :
                new ObjectParameter("ID_LH", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SanPham_SearchLH_Result>("SanPham_SearchLH", iD_LHParameter);
        }
    
        public virtual ObjectResult<SanPham_SearchNH_Result> SanPham_SearchNH(string iD_NH)
        {
            var iD_NHParameter = iD_NH != null ?
                new ObjectParameter("ID_NH", iD_NH) :
                new ObjectParameter("ID_NH", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SanPham_SearchNH_Result>("SanPham_SearchNH", iD_NHParameter);
        }
    
        public virtual ObjectResult<SanPham_SearchTenSP_Result> SanPham_SearchTenSP(string name_SP)
        {
            var name_SPParameter = name_SP != null ?
                new ObjectParameter("Name_SP", name_SP) :
                new ObjectParameter("Name_SP", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SanPham_SearchTenSP_Result>("SanPham_SearchTenSP", name_SPParameter);
        }
    
        public virtual ObjectResult<SanPham_SearchTinhTrang_Result> SanPham_SearchTinhTrang(string tinhTrang)
        {
            var tinhTrangParameter = tinhTrang != null ?
                new ObjectParameter("TinhTrang", tinhTrang) :
                new ObjectParameter("TinhTrang", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SanPham_SearchTinhTrang_Result>("SanPham_SearchTinhTrang", tinhTrangParameter);
        }
    
        public virtual ObjectResult<SANPHAM> SanPham_Search_General(Nullable<int> iD_NH, Nullable<int> iD_HSX, Nullable<int> iD_LH)
        {
            var iD_NHParameter = iD_NH.HasValue ?
                new ObjectParameter("ID_NH", iD_NH) :
                new ObjectParameter("ID_NH", typeof(int));
    
            var iD_HSXParameter = iD_HSX.HasValue ?
                new ObjectParameter("ID_HSX", iD_HSX) :
                new ObjectParameter("ID_HSX", typeof(int));
    
            var iD_LHParameter = iD_LH.HasValue ?
                new ObjectParameter("ID_LH", iD_LH) :
                new ObjectParameter("ID_LH", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SANPHAM>("SanPham_Search_General", iD_NHParameter, iD_HSXParameter, iD_LHParameter);
        }
    
        public virtual ObjectResult<SANPHAM> SanPham_Search_General(Nullable<int> iD_NH, Nullable<int> iD_HSX, Nullable<int> iD_LH, MergeOption mergeOption)
        {
            var iD_NHParameter = iD_NH.HasValue ?
                new ObjectParameter("ID_NH", iD_NH) :
                new ObjectParameter("ID_NH", typeof(int));
    
            var iD_HSXParameter = iD_HSX.HasValue ?
                new ObjectParameter("ID_HSX", iD_HSX) :
                new ObjectParameter("ID_HSX", typeof(int));
    
            var iD_LHParameter = iD_LH.HasValue ?
                new ObjectParameter("ID_LH", iD_LH) :
                new ObjectParameter("ID_LH", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SANPHAM>("SanPham_Search_General", mergeOption, iD_NHParameter, iD_HSXParameter, iD_LHParameter);
        }
    
        public virtual ObjectResult<SANPHAM> SanPham_Search_HangSX(string iD_HSX)
        {
            var iD_HSXParameter = iD_HSX != null ?
                new ObjectParameter("ID_HSX", iD_HSX) :
                new ObjectParameter("ID_HSX", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SANPHAM>("SanPham_Search_HangSX", iD_HSXParameter);
        }
    
        public virtual ObjectResult<SANPHAM> SanPham_Search_HangSX(string iD_HSX, MergeOption mergeOption)
        {
            var iD_HSXParameter = iD_HSX != null ?
                new ObjectParameter("ID_HSX", iD_HSX) :
                new ObjectParameter("ID_HSX", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SANPHAM>("SanPham_Search_HangSX", mergeOption, iD_HSXParameter);
        }
    
        public virtual ObjectResult<SANPHAM> SanPham_Search_LoaiHang(string iD_LH)
        {
            var iD_LHParameter = iD_LH != null ?
                new ObjectParameter("ID_LH", iD_LH) :
                new ObjectParameter("ID_LH", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SANPHAM>("SanPham_Search_LoaiHang", iD_LHParameter);
        }
    
        public virtual ObjectResult<SANPHAM> SanPham_Search_LoaiHang(string iD_LH, MergeOption mergeOption)
        {
            var iD_LHParameter = iD_LH != null ?
                new ObjectParameter("ID_LH", iD_LH) :
                new ObjectParameter("ID_LH", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SANPHAM>("SanPham_Search_LoaiHang", mergeOption, iD_LHParameter);
        }
    
        public virtual ObjectResult<SANPHAM> SanPham_Search_NH(string iD_NH)
        {
            var iD_NHParameter = iD_NH != null ?
                new ObjectParameter("ID_NH", iD_NH) :
                new ObjectParameter("ID_NH", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SANPHAM>("SanPham_Search_NH", iD_NHParameter);
        }
    
        public virtual ObjectResult<SANPHAM> SanPham_Search_NH(string iD_NH, MergeOption mergeOption)
        {
            var iD_NHParameter = iD_NH != null ?
                new ObjectParameter("ID_NH", iD_NH) :
                new ObjectParameter("ID_NH", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SANPHAM>("SanPham_Search_NH", mergeOption, iD_NHParameter);
        }
    
        public virtual ObjectResult<SANPHAM> SanPham_Search_TenSP(string name_SP)
        {
            var name_SPParameter = name_SP != null ?
                new ObjectParameter("Name_SP", name_SP) :
                new ObjectParameter("Name_SP", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SANPHAM>("SanPham_Search_TenSP", name_SPParameter);
        }
    
        public virtual ObjectResult<SANPHAM> SanPham_Search_TenSP(string name_SP, MergeOption mergeOption)
        {
            var name_SPParameter = name_SP != null ?
                new ObjectParameter("Name_SP", name_SP) :
                new ObjectParameter("Name_SP", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SANPHAM>("SanPham_Search_TenSP", mergeOption, name_SPParameter);
        }
    
        public virtual ObjectResult<SANPHAM> SanPham_Search_TinhTrang(string tinhTrang)
        {
            var tinhTrangParameter = tinhTrang != null ?
                new ObjectParameter("TinhTrang", tinhTrang) :
                new ObjectParameter("TinhTrang", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SANPHAM>("SanPham_Search_TinhTrang", tinhTrangParameter);
        }
    
        public virtual ObjectResult<SANPHAM> SanPham_Search_TinhTrang(string tinhTrang, MergeOption mergeOption)
        {
            var tinhTrangParameter = tinhTrang != null ?
                new ObjectParameter("TinhTrang", tinhTrang) :
                new ObjectParameter("TinhTrang", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SANPHAM>("SanPham_Search_TinhTrang", mergeOption, tinhTrangParameter);
        }
    
        public virtual ObjectResult<SanPham_Search_3_Result> SanPham_Search_3(string iD_NH, string iD_HSX, string iD_LH)
        {
            var iD_NHParameter = iD_NH != null ?
                new ObjectParameter("ID_NH", iD_NH) :
                new ObjectParameter("ID_NH", typeof(string));
    
            var iD_HSXParameter = iD_HSX != null ?
                new ObjectParameter("ID_HSX", iD_HSX) :
                new ObjectParameter("ID_HSX", typeof(string));
    
            var iD_LHParameter = iD_LH != null ?
                new ObjectParameter("ID_LH", iD_LH) :
                new ObjectParameter("ID_LH", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SanPham_Search_3_Result>("SanPham_Search_3", iD_NHParameter, iD_HSXParameter, iD_LHParameter);
        }
    }
}
