//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace phone_BETA_1.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    using System.ComponentModel.DataAnnotations;

    public partial class NHANVIEN
    {
        [DisplayName("Mã nhân viên:")]
        public int ID_Admin { get; set; }
        [DisplayName("Tên nhân viên:")]
        public string Name_Admin { get; set; }
        [DisplayName("Giới tính:")]
        public string Sex { get; set; }
        [DataType(DataType.Date)]
        [DisplayFormat(DataFormatString = "{0: yyyy-MM-dd}", ApplyFormatInEditMode = true)]
        public Nullable<System.DateTime> DateOfBirth { get; set; }
        [DataType(DataType.Date)]
        [DisplayFormat(DataFormatString = "{0: yyyy-MM-dd}", ApplyFormatInEditMode = true)]
        public Nullable<System.DateTime> DateOfWork { get; set; }
        [DisplayName("Lương:")]
        public Nullable<double> Salary { get; set; }

        public virtual ADMIN ADMIN { get; set; }
    }
}
