//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace phone_BETA_1.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    using System.ComponentModel.DataAnnotations;
    using System.Web;

    public partial class SANPHAM
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public SANPHAM()
        {
            this.CHITIET_HOADON = new HashSet<CHITIET_HOADON>();
        }

        [DisplayName("Mã sản phẩm:")]
        public int ID_SP { get; set; }
        [DisplayName("Tên sản phẩm:")]
        public string Name_SP { get; set; }
        [DisplayName("Giá tiền (VND):")]
        public Nullable<double> Price_SP { get; set; }
        [DisplayName("Năm sản xuất:")]
        public Nullable<double> Year_SP { get; set; }
        [DisplayName("Trả góp:")]
        public Nullable<double> TraGop { get; set; }
        [DisplayName("Tình trạng:")]
        public string TinhTrang { get; set; }
        [DisplayName("Phụ kiện đi kèm:")]
        public string PhuKien { get; set; }
        [DisplayName("Ảnh sản phẩm:")]
        public string Photo { get; set; }
        [DisplayName("Nhóm sản phẩm:")]
        public Nullable<int> ID_NH { get; set; }
        [DisplayName("Loại sản phẩm:")]
        public Nullable<int> ID_LH { get; set; }
        [DisplayName("Hãng sản xuất:")]
        public Nullable<int> ID_HSX { get; set; }

        public HttpPostedFileBase ImageFile { get; set; }

        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CHITIET_HOADON> CHITIET_HOADON { get; set; }
        public virtual HANG_SX HANG_SX { get; set; }
        public virtual LOAIHANG LOAIHANG { get; set; }
        public virtual NHOMHANG NHOMHANG { get; set; }
    }
}
